const ERROR_UNEXPECTED = 500;
const ERROR_VALIDATION = 400;
const ERROR_NOT_FOUND = 404;
const SUCCESS_CODE = 201;

module.exports = {
  ERROR_UNEXPECTED, ERROR_VALIDATION, ERROR_NOT_FOUND, SUCCESS_CODE,
};
